### ISSUE TITLE
Walk Multipart Email: initial_value must be str or None, not bytes

### ISSUE THREAD

**Issue by bobmeliev** [lasselindqvist/robotframework-imaplibrary#4] opened 2019-11-21 05:26 UTC
Walk Multipart Email is failing with error:

> TypeError: initial_value must be str or None, not bytes

Wait For Email is returning index as bytes but converting the index into string doesn't help.

```
    ${latest}=    Wait For Email    subject=Welcome!    timeout=60
    ${type}=    Evaluate    type($latest)    
    ${latest_str}=    Convert To String    ${latest}
    ${type}=    Evaluate    type($latest_str)    
    ${parts}=    Walk Multipart Email    ${latest_str}
```

```
20191121 10:17:59.267 : INFO : ${latest} = 12
20191121 10:17:59.284 : INFO : ${type} = <class 'bytes'>
20191121 10:17:59.288 : INFO : ${latest_str} = 12
20191121 10:17:59.292 : INFO : ${type} = <class 'str'>
20191121 10:17:59.533 : FAIL : TypeError: initial_value must be str or None, not bytes
```

**Comment by tanmay-plivo** [comment] 2020-02-11 10:41
@bobmeliev , have you been able to find solution to  the issue.

**Comment by Tanmay-Agrawal** [comment] 2020-02-11 10:43
@bobmeliev , @lasselindqvist  have you been able to find a solution to the problem?

**Comment by lasselindqvist** [comment] 2020-02-11 16:35
I haven't been looking into this, but will happily merge if there is a solution to a problem.

**Comment by ulkanti** [comment] 2020-02-26 12:21
In __init__.py from email import message_from_bytes instead of from email import message_from_string and in def walk_multipart_email(self, email_index):  the same change should fix the issue. 

That is if you are using python 3. If you are using python2, the current setup would work. So the library now only for one python version only.

**Comment by lasselindqvist** [comment] 2020-03-03 20:34
>  import message_from_string and in def walk_multipart_email(self, email_index)

If this is the case, I would prefer to fix it even if the quick fix meant Python 2 no longer works, since it is EOL anyway.

**Comment by lynhbn** [comment] 2020-07-04 19:05
@lasselindqvist This one can easily be fixed by changing:
`data = self._imap.uid('fetch', email_index, '(RFC822)')[1][0][1]`
into:
`data = self._imap.uid('fetch', email_index, '(RFC822)')[1][0][1].decode('utf-8')`
in __init__.py line **348**
Sorry I'm unable to help you to create a pull request

**Comment by lynhbn** [comment] 2020-07-04 19:11
One another point, the fuction open_link_from_email also does not work with Python 3.
Please help to fix it at line 255:
`content_type = resp.headers.getheader('content-type')`
change into:
`content_type = resp.headers.get('content-type')`
Then everything will be okay
Looking forward to your answer soon!

**Comment by lasselindqvist** [comment] 2020-07-15 08:42
> 
> 
> One another point, the fuction open_link_from_email also does not work with Python 3.
> Please help to fix it at line 255:
> `content_type = resp.headers.getheader('content-type')`
> change into:
> `content_type = resp.headers.get('content-type')`
> Then everything will be okay
> Looking forward to your answer soon!

I'm happy to merge and release, if you can provide a PR for it.

**Comment by azad-DH** [comment] 2020-09-11 17:51
Since I was trying to fix the same issue, [I created a PR](https://github.com/rickypc/robotframework-imaplibrary/pull/28) now.
I'd be very grateful if you could review and approve it, so we can finally use ImapLibary with Python 3. 🙏

I also added lynhbn's suggestion in a second commit.

**Comment by lasselindqvist** [comment] 2020-09-11 19:11
Can you make the PR in this repository? You made it in rickpc original.

**Comment by azad-DH** [comment] 2020-09-15 09:55
~~Oh ok, yeah sure I'll make the PR here as well.~~~

Actually, when I try to create a PR in this repository, the PR is just created in rickypc again automatically.

@lasselindqvist Can you merge the PR [over there](https://github.com/rickypc/robotframework-imaplibrary/pull/28)?

**Comment by lasselindqvist** [comment] 2020-09-15 17:28
I have no rights to that repository, and the owner of it seems to be inactive, so I cannot do anything to those PRs.

**Comment by azad-DH** [comment] 2020-09-15 17:35
Ah that's what I feared. ~~I'll create a PR in your repo now.~~
Nope, I got no access rights to create a PR in your repo. I can only do a fork, or can you give me access rights for your repo?

**Comment by azad-DH** [comment] 2020-09-15 17:44
Ok I managed to create a PR in your repo:
https://github.com/lasselindqvist/robotframework-imaplibrary2/pull/13

I don't know why I can't assign a reviewer, but I'm assuming you should be able to merge it from there. :)

**Comment by azad-DH** [comment] 2020-09-17 09:11
Thanks for merging!

**Comment by zuzakrol** [comment] 2020-10-08 13:32
@azad-DH @lasselindqvist  Hi, I think the current solution does not work as I'm getting the following error:
`AttributeError: 'str' object has no attribute 'decode'`
That's because inside the `message_from_bytes` method it's trying to decode `data` which is already a string:
```
data = self._imap.uid('fetch', email_index, '(RFC822)')[1][0][1].decode('UTF-8')
msg = message_from_bytes(data)
```
It can be fixed by either removing the `.decode('UTF-8')` part or going back to using `message_from_string`

**Comment by azad-DH** [comment] 2020-10-08 13:35
Hm that's odd, I didn't encounter that issue while trying it out. In what context did it come up for you?

From the two solutions you suggested, I would definitely vote for removing the `.decode('UTF-8')` part as going back to `message_from_string` would just make it incompatible with Python3 again.

**Comment by zuzakrol** [comment] 2020-10-08 13:57
In my project we were using Python 2.7 and the older version of ImapLibrary. We had to upgrade to Python 3 and that's when we encountered the error mentioned in the topic. I've updated the ImapLibrary to the newest version of ImapLibrary2 but got an error described above.

Removing the .decode part sound good to me as well :) Would it be possible for you to create a PR with that change?

**Comment by azad-DH** [comment] 2020-10-08 14:28
@zuzakrol Just to make sure: did you adjust the import in the requirements.txt and ran the install command again?
Because otherwise you'd be still running the old ImapLibrary.

**Comment by zuzakrol** [comment] 2020-10-09 06:11
You mean the import in the Robot test suite?
`*** Settings ***
Library    ImapLibrary2`
Yes, I did that of course :)

**Comment by zuzakrol** [comment] 2020-10-15 07:26
@azad-DH @lasselindqvist I've tried to create a branch with a fix but it looks like I don't have permissions for this repo :(

**Closed as completed** 2020-10-16 21:01 UTC

**Comment by navrkald** [comment] 2020-10-20 12:36
Hello @lasselindqvist thx for merging fixed version of code. Pls could you be so kind to release new version of this awesome library so we can use new fixed version in our project?

**Comment by azad-DH** [comment] 2020-10-20 12:44
> Pls could you be so kind to release new version of this awesome library so we can use new fixed version in our project?

@navrkald What do you mean?
The change has been merged, you can already use the new "version".
Just gotta run the install command again.

**Comment by lasselindqvist** [comment] 2020-10-20 19:48
Yes the new version is usable if you download the code and use master branch. But they likely mean for me to upload it to Pypi, which I intend to do. Currently the documentation is just causing some headache, since Pypi rejects it due to syntax errors. I used to be able to upload it fine on another machine though for some reason (maybe different tool versions) so I will try to get it done one way or the other.

**Comment by azad-DH** [comment] 2020-10-21 10:35
Ah I see, never used Pypi, sounds like overcomplicating a simple thing to me. 😂

**Comment by desh567** [comment] 2020-10-21 21:34
Could you please let me know when the new version available?

**Comment by desh567** [comment] 2020-10-22 11:53
> Yes the new version is usable if you download the code and use master branch. But they likely mean for me to upload it to Pypi, which I intend to do. Currently the documentation is just causing some headache, since Pypi rejects it due to syntax errors. I used to be able to upload it fine on another machine though for some reason (maybe different tool versions) so I will try to get it done one way or the other.

Hi,

We are waiting to use this changes . Could you please let us know when the new version will be available?

**Comment by lasselindqvist** [comment] 2020-10-22 20:06
Hi. 0.3.8 should now be available. Let me know if it works for you guys.
ping @desh567 @navrkald @zuzakrol

**Comment by azad-DH** [comment] 2020-10-23 12:14
During a test run with Python 3 yesterday, `TypeError: initial_value must be str or None, not bytes` occured again.

Could it be because `.decode('UTF-8')` was removed in https://github.com/lasselindqvist/robotframework-imaplibrary2/commit/d51922ff0ad468cdeff7440cbfa6f1e0740547cf?

It was working fine before that change (hadn't used it for a while before yesterday).

**Comment by lasselindqvist** [comment] 2020-10-23 12:29
> 
> 
> During a test run with Python 3 yesterday, `TypeError: initial_value must be str or None, not bytes` occured again.
> 
> Could it be because `.decode('UTF-8')` was removed in [d51922f](https://github.com/lasselindqvist/robotframework-imaplibrary2/commit/d51922ff0ad468cdeff7440cbfa6f1e0740547cf)?
> 
> It was working fine before that change (hadn't used it for a while before yesterday).

Likely is. So it seems in some cases it comes as bytes, some cases string. Dirty-hack would be to try to decode it. The contents come from https://docs.python.org/3/library/imaplib.html#imaplib.IMAP4.uid and it doesn't really say what the returned response is. And I don't really know how that module behaves.

**Comment by azad-DH** [comment] 2020-10-23 12:35
Oh wait, never mind, I think the issue was something else.
Just discovered that our test suite still imported Imaplibrary2 0.3.4, so it wasn't using my fix. 🤦‍♂️

**Comment by azad-DH** [comment] 2020-10-23 13:10
Yep, that was the cause, so everything's fine. 👍 
Just did a new test run with updated import statement and the issue's not coming up anymore.

**Comment by lasselindqvist** [comment] 2020-10-23 14:17
Good. :) I was ready the blame the underlying IMAP library. :D
